export const unhandledMortgageFormat = original => {
  return {
    buguid: original.buguid,
    companyName: original.公司名称,
    projectName: original.项目名称,
    projGUID: original.ProjGUID,
    buildingNo: original.房号,
    tradeGUID: original.TradeGUID,
    customName: original.客户姓名,
    orderDate: original.认购日期,
    // roomNum: original.足签日期,
    // roomNum: original.网签日期,
    // roomNum: original.对接人员,
    contractSum: original.合同总价,
    // roomNum: original.置业顾问,
    saleServiceGUID: original.SaleServiceGUID,
    // roomNum: original.服务进程,
    // roomNum: original.二级分类,
    // roomNum: original.按揭进程,
    sequence: original.Sequence,
    lastProcessingDate: original.最后办理日期,
    // roomNum: original.按揭银行,
    // roomNum: original.按揭金额,
    // roomNum: original.公积金银行,
    // roomNum: original.公积金金额,
    customPhone: original.电话号码,
    remark: original.备注,
    isFirstBatchMaterial: original.是否首期材料,
    isNoInformationReceived: original.未收到资料,
    mortgageOverdueDays: original.按揭逾期天数,
    commonFoundOverdueDay: original.公积金逾期天数
  };
};

export const handlingMortgageFormat = original => {
  return {
    buguid: original.buguid,
    companyName: original.公司名称,
    projectName: original.项目名称,
    rojGUID: original.ProjGUID,
    buildingNo: original.房号,
    tradeGUID: original.TradeGUID,
    customName: original.客户姓名,
    orderDate: original.认购日期,
    // roomNum: original.足签日期,
    // roomNum: original.网签日期,
    // roomNum: original.对接人员,
    contractSum: original.合同总价,
    // roomNum: original.置业顾问,
    // roomNum: original.SaleServiceGUID,
    // roomNum: original.服务进程,
    // roomNum: original.二级分类,
    // roomNum: original.按揭进程,
    sequence: original.Sequence,
    lastProcessingDate: original.最后办理日期,
    // roomNum: original.按揭银行,
    // roomNum: original.按揭金额,
    // roomNum: original.公积金银行,
    // roomNum: original.公积金金额,
    customPhone: original.电话号码,
    remark: original.备注,
    isFirstBatchMaterial: original.是否首期材料,
    isNoInformationReceived: original.未收到资料,
    mortgageOverdueDays: original.按揭逾期天数,
    commonFoundOverdueDay: original.公积金逾期天数
  };
};

export const handledMortgageFormat = original => {
  return {
    buguid: original.buguid,
    companyName: original.公司名称,
    projectName: original.项目名称,
    rojGUID: original.ProjGUID,
    buildingNo: original.房号,
    tradeGUID: original.TradeGUID,
    customName: original.客户姓名,
    orderDate: original.认购日期,
    // roomNum: original.足签日期,
    // roomNum: original.网签日期,
    // roomNum: original.对接人员,
    contractSum: original.合同总价,
    // roomNum: original.置业顾问,
    // roomNum: original.SaleServiceGUID,
    // roomNum: original.服务进程,
    // roomNum: original.二级分类,
    // roomNum: original.按揭进程,
    sequence: original.Sequence,
    lastProcessingDate: original.最后办理日期,
    // roomNum: original.按揭银行,
    // roomNum: original.按揭金额,
    // roomNum: original.公积金银行,
    // roomNum: original.公积金金额,
    customPhone: original.电话号码,
    remark: original.备注,
    isFirstBatchMaterial: original.是否首期材料,
    isNoInformationReceived: original.未收到资料,
    mortgageOverdueDays: original.按揭逾期天数,
    commonFoundOverdueDay: original.公积金逾期天数
  };
};
